global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: opensearch
    scrape_interval: 10s
    metrics_path: "/_prometheus/metrics"
    scheme: https
    tls_config:
      insecure_skip_verify: false
      ca_file: "/etc/prometheus/root-ca.crt"
    static_configs:
      - targets:
        - opensearch-node-1:9200
    basic_auth:
      username: 'admin'
      password: 'admin'